// Generated by ffigen from include/prism/prism_core.h — DO NOT EDIT.
// ignore_for_file: type=lint, doc_directive_unknown

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Generated from the Prism Engine core C ABI. DO NOT EDIT by hand.
class PrismCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PrismCoreBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PrismCoreBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// "MAJOR.MINOR.PATCH" of the linked library. Compare against the macros above.
  ffi.Pointer<ffi.Char> prism_version() {
    return _prism_version();
  }

  late final _prism_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'prism_version');
  late final _prism_version =
      _prism_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Static, human-readable description; never NULL.
  ffi.Pointer<ffi.Char> prism_result_description(
    prism_result result,
  ) {
    return _prism_result_description(
      result.value,
    );
  }

  late final _prism_result_descriptionPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>>(
      'prism_result_description');
  late final _prism_result_description = _prism_result_descriptionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  /// All defaults (aqademiq profile, UTC, spec cadence).
  prism_config prism_config_default() {
    return _prism_config_default();
  }

  late final _prism_config_defaultPtr =
      _lookup<ffi.NativeFunction<prism_config Function()>>(
          'prism_config_default');
  late final _prism_config_default =
      _prism_config_defaultPtr.asFunction<prism_config Function()>();

  /// Create an engine. `config` may be NULL for all defaults. On success writes the new
  /// handle to *out_core. The handle must be released with prism_destroy.
  prism_result prism_create(
    ffi.Pointer<prism_config> config,
    ffi.Pointer<ffi.Pointer<prism_core>> out_core,
  ) {
    return prism_result.fromValue(_prism_create(
      config,
      out_core,
    ));
  }

  late final _prism_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_config>,
              ffi.Pointer<ffi.Pointer<prism_core>>)>>('prism_create');
  late final _prism_create = _prism_createPtr.asFunction<
      int Function(
          ffi.Pointer<prism_config>, ffi.Pointer<ffi.Pointer<prism_core>>)>();

  /// Stops everything still running (inference thread, built-in device) and frees the
  /// handle. NULL is a no-op.
  void prism_destroy(
    ffi.Pointer<prism_core> core,
  ) {
    return _prism_destroy(
      core,
    );
  }

  late final _prism_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<prism_core>)>>(
          'prism_destroy');
  late final _prism_destroy =
      _prism_destroyPtr.asFunction<void Function(ffi.Pointer<prism_core>)>();

  /// Load a scene manifest (scenes.json; stem paths resolve relative to it). Decodes and
  /// preloads every stem of the default scene — file I/O happens HERE, never at render
  /// time. Call once, before prism_start / any rendering. INVALID_STATE after start.
  prism_result prism_load_scene(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<ffi.Char> scenes_json_path,
  ) {
    return prism_result.fromValue(_prism_load_scene(
      core,
      scenes_json_path,
    ));
  }

  late final _prism_load_scenePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>,
              ffi.Pointer<ffi.Char>)>>('prism_load_scene');
  late final _prism_load_scene = _prism_load_scenePtr.asFunction<
      int Function(ffi.Pointer<prism_core>, ffi.Pointer<ffi.Char>)>();

  /// Start the engine: emits the neutral PSV (spec §6) and launches the internal inference
  /// thread (evaluates on the cadence + significant-change rule). Requires a loaded scene.
  /// INVALID_STATE if already started. Restart after prism_stop is allowed; the restart's
  /// neutral vector continues the sequence (see prism_psv.sequence).
  prism_result prism_start(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_start(
      core,
    ));
  }

  late final _prism_startPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>('prism_start');
  late final _prism_start =
      _prism_startPtr.asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// Stop the inference thread (and the built-in device if running). Idempotent.
  prism_result prism_stop(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_stop(
      core,
    ));
  }

  late final _prism_stopPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>('prism_stop');
  late final _prism_stop =
      _prism_stopPtr.asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// --- Event ingress -------------------------------------------------------------------
  /// Platform shells capture raw events and forward them; no inference logic lives on the
  /// host side. Timestamps are epoch milliseconds from the host clock. App identity never
  /// crosses this boundary: a switch is a bare timestamp, idle is a duration, tasks are
  /// due instants plus priorities. Thread-safe; never call from the render callback.
  prism_result prism_report_app_switch(
    ffi.Pointer<prism_core> core,
    int t_ms,
  ) {
    return prism_result.fromValue(_prism_report_app_switch(
      core,
      t_ms,
    ));
  }

  late final _prism_report_app_switchPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<prism_core>, ffi.Int64)>>('prism_report_app_switch');
  late final _prism_report_app_switch = _prism_report_app_switchPtr
      .asFunction<int Function(ffi.Pointer<prism_core>, int)>();

  prism_result prism_report_idle(
    ffi.Pointer<prism_core> core,
    int t_ms,
    int idle_ms,
  ) {
    return prism_result.fromValue(_prism_report_idle(
      core,
      t_ms,
      idle_ms,
    ));
  }

  late final _prism_report_idlePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>, ffi.Int64,
              ffi.Int64)>>('prism_report_idle');
  late final _prism_report_idle = _prism_report_idlePtr
      .asFunction<int Function(ffi.Pointer<prism_core>, int, int)>();

  /// Replace the full task-deadline snapshot (matches how hosts observe task lists).
  /// `tasks` may be NULL when `count` is 0 (an empty list is a valid state). Task lists are
  /// human-scale: count > 4096 is rejected as INVALID_ARGUMENT (this also shields the
  /// boundary from negative lengths cast to size_t). No C++ exception ever crosses this
  /// ABI; internal failures surface as error codes.
  prism_result prism_report_task_deadlines(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<prism_task_deadline> tasks,
    int count,
  ) {
    return prism_result.fromValue(_prism_report_task_deadlines(
      core,
      tasks,
      count,
    ));
  }

  late final _prism_report_task_deadlinesPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<prism_core>,
              ffi.Pointer<prism_task_deadline>,
              ffi.Size)>>('prism_report_task_deadlines');
  late final _prism_report_task_deadlines =
      _prism_report_task_deadlinesPtr.asFunction<
          int Function(ffi.Pointer<prism_core>,
              ffi.Pointer<prism_task_deadline>, int)>();

  /// Copy the most recently emitted PSV into *out. INVALID_STATE before prism_start (the
  /// cold-start vector exists from start onward). Thread-safe.
  prism_result prism_get_psv(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<prism_psv> out,
  ) {
    return prism_result.fromValue(_prism_get_psv(
      core,
      out,
    ));
  }

  late final _prism_get_psvPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>,
              ffi.Pointer<prism_psv>)>>('prism_get_psv');
  late final _prism_get_psv = _prism_get_psvPtr.asFunction<
      int Function(ffi.Pointer<prism_core>, ffi.Pointer<prism_psv>)>();

  /// Sample rate of the loaded scene's stems (0 before a scene is loaded). Mono float32.
  int prism_sample_rate(
    ffi.Pointer<prism_core> core,
  ) {
    return _prism_sample_rate(
      core,
    );
  }

  late final _prism_sample_ratePtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<prism_core>)>>(
          'prism_sample_rate');
  late final _prism_sample_rate =
      _prism_sample_ratePtr.asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// Render `frame_count` mono float32 frames into out_frames. Real-time safe: wait-free,
  /// no allocation, no locks, no I/O, no logging. Single audio thread only. Before a scene
  /// is loaded, fills silence and returns INVALID_STATE.
  prism_result prism_render(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<ffi.Float> out_frames,
    int frame_count,
  ) {
    return prism_result.fromValue(_prism_render(
      core,
      out_frames,
      frame_count,
    ));
  }

  late final _prism_renderPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>,
              ffi.Pointer<ffi.Float>, ffi.Uint32)>>('prism_render');
  late final _prism_render = _prism_renderPtr.asFunction<
      int Function(ffi.Pointer<prism_core>, ffi.Pointer<ffi.Float>, int)>();

  /// Open and start the built-in playback device (renders internally; do not also call
  /// prism_render). Requires a loaded scene. INVALID_STATE if already running.
  prism_result prism_device_start(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_device_start(
      core,
    ));
  }

  late final _prism_device_startPtr = _lookup<
          ffi
          .NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>(
      'prism_device_start');
  late final _prism_device_start = _prism_device_startPtr
      .asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// Stop and close the built-in device. Idempotent.
  prism_result prism_device_stop(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_device_stop(
      core,
    ));
  }

  late final _prism_device_stopPtr = _lookup<
          ffi
          .NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>(
      'prism_device_stop');
  late final _prism_device_stop =
      _prism_device_stopPtr.asFunction<int Function(ffi.Pointer<prism_core>)>();
}

typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.LongLong;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLongLong;
typedef Dart__uint64_t = int;
typedef __darwin_intptr_t = ffi.Long;
typedef Dart__darwin_intptr_t = int;
typedef __darwin_natural_t = ffi.UnsignedInt;
typedef Dart__darwin_natural_t = int;

/// The rune type below is declared to be an ``int'' instead of the more natural
/// ``unsigned long'' or ``long''.  Two things are happening here.  It is not
/// unsigned so that EOF (-1) can be naturally assigned to it and used.  Also,
/// it looks like 10646 will be a 31 bit standard.  This means that if your
/// ints cannot hold 32 bits, you will be in trouble.  The reason an int was
/// chosen over a long is that the is*() and to*() routines take ints (says
/// ANSI C), but they use __darwin_ct_rune_t instead of int.  By changing it
/// here, you lose a bit of ANSI conformance, but your programs will still
/// work.
///
/// NOTE: rune_t is not covered by ANSI nor other standards, and should not
/// be instantiated outside of lib/libc/locale.  Use wchar_t.  wchar_t and
/// rune_t must be the same type.  Also wint_t must be no narrower than
/// wchar_t, and should also be able to hold all members of the largest
/// character set plus one extra value (WEOF). wint_t must be at least 16 bits.
typedef __darwin_ct_rune_t = ffi.Int;
typedef Dart__darwin_ct_rune_t = int;

/// mbstate_t is an opaque object to keep conversion state, during multibyte
/// stream conversions.  The content must not be referenced by user programs.
final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  /// for alignment
  @ffi.LongLong()
  external int _mbstateL;
}

typedef __darwin_mbstate_t = __mbstate_t;
typedef __darwin_ptrdiff_t = ffi.Long;
typedef Dart__darwin_ptrdiff_t = int;
typedef __darwin_size_t = ffi.UnsignedLong;
typedef Dart__darwin_size_t = int;
typedef __builtin_va_list = ffi.Pointer<ffi.Char>;
typedef __darwin_va_list = __builtin_va_list;
typedef __darwin_wchar_t = ffi.Int;
typedef Dart__darwin_wchar_t = int;
typedef __darwin_rune_t = __darwin_wchar_t;
typedef __darwin_wint_t = ffi.Int;
typedef Dart__darwin_wint_t = int;
typedef __darwin_clock_t = ffi.UnsignedLong;
typedef Dart__darwin_clock_t = int;
typedef __darwin_socklen_t = __uint32_t;
typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
typedef __darwin_blkcnt_t = __int64_t;
typedef __darwin_blksize_t = __int32_t;
typedef __darwin_dev_t = __int32_t;
typedef __darwin_fsblkcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsblkcnt_t = int;
typedef __darwin_fsfilcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsfilcnt_t = int;
typedef __darwin_gid_t = __uint32_t;
typedef __darwin_id_t = __uint32_t;
typedef __darwin_ino64_t = __uint64_t;
typedef __darwin_ino_t = __darwin_ino64_t;
typedef __darwin_mach_port_name_t = __darwin_natural_t;
typedef __darwin_mach_port_t = __darwin_mach_port_name_t;
typedef __darwin_mode_t = __uint16_t;
typedef __darwin_off_t = __int64_t;
typedef __darwin_pid_t = __int32_t;
typedef __darwin_sigset_t = __uint32_t;
typedef __darwin_suseconds_t = __int32_t;
typedef __darwin_uid_t = __uint32_t;
typedef __darwin_useconds_t = __uint32_t;

final class __darwin_pthread_handler_rec extends ffi.Struct {
  /// Routine to call
  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      __routine;

  /// Argument to pass
  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;
}

final class _opaque_pthread_attr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_condattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutexattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_once_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlock_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([192])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_rwlockattr_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

  @ffi.Array.multi([8176])
  external ffi.Array<ffi.Char> __opaque;
}

typedef __darwin_pthread_attr_t = _opaque_pthread_attr_t;
typedef __darwin_pthread_cond_t = _opaque_pthread_cond_t;
typedef __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
typedef __darwin_pthread_key_t = ffi.UnsignedLong;
typedef Dart__darwin_pthread_key_t = int;
typedef __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
typedef __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
typedef __darwin_pthread_once_t = _opaque_pthread_once_t;
typedef __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
typedef __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
typedef __darwin_pthread_t = ffi.Pointer<_opaque_pthread_t>;
typedef __darwin_nl_item = ffi.Int;
typedef Dart__darwin_nl_item = int;
typedef __darwin_wctrans_t = ffi.Int;
typedef Dart__darwin_wctrans_t = int;
typedef __darwin_wctype_t = __uint32_t;
typedef u_int8_t = ffi.UnsignedChar;
typedef Dartu_int8_t = int;
typedef u_int16_t = ffi.UnsignedShort;
typedef Dartu_int16_t = int;
typedef u_int32_t = ffi.UnsignedInt;
typedef Dartu_int32_t = int;
typedef u_int64_t = ffi.UnsignedLongLong;
typedef Dartu_int64_t = int;
typedef register_t = ffi.Int64;
typedef Dartregister_t = int;
typedef user_addr_t = u_int64_t;
typedef user_size_t = u_int64_t;
typedef user_ssize_t = ffi.Int64;
typedef Dartuser_ssize_t = int;
typedef user_long_t = ffi.Int64;
typedef Dartuser_long_t = int;
typedef user_ulong_t = u_int64_t;
typedef user_time_t = ffi.Int64;
typedef Dartuser_time_t = int;
typedef user_off_t = ffi.Int64;
typedef Dartuser_off_t = int;
typedef syscall_arg_t = u_int64_t;
typedef ptrdiff_t = __darwin_ptrdiff_t;
typedef rsize_t = __darwin_size_t;
typedef wint_t = __darwin_wint_t;

/// 7.18.1.2 Minimum-width integer types
typedef int_least8_t = ffi.Int8;
typedef Dartint_least8_t = int;
typedef int_least16_t = ffi.Int16;
typedef Dartint_least16_t = int;
typedef int_least32_t = ffi.Int32;
typedef Dartint_least32_t = int;
typedef int_least64_t = ffi.Int64;
typedef Dartint_least64_t = int;
typedef uint_least8_t = ffi.Uint8;
typedef Dartuint_least8_t = int;
typedef uint_least16_t = ffi.Uint16;
typedef Dartuint_least16_t = int;
typedef uint_least32_t = ffi.Uint32;
typedef Dartuint_least32_t = int;
typedef uint_least64_t = ffi.Uint64;
typedef Dartuint_least64_t = int;

/// 7.18.1.3 Fastest-width integer types
typedef int_fast8_t = ffi.Int8;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Int16;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Int32;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Int64;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.Uint8;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.Uint16;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.Uint32;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.Uint64;
typedef Dartuint_fast64_t = int;
typedef intmax_t = ffi.Long;
typedef Dartintmax_t = int;
typedef uintmax_t = ffi.UnsignedLong;
typedef Dartuintmax_t = int;

enum prism_result {
  PRISM_OK(0),

  /// null/malformed parameter
  PRISM_ERROR_INVALID_ARGUMENT(1),

  /// call violates the lifecycle (see per-function docs)
  PRISM_ERROR_INVALID_STATE(2),

  /// scene manifest or stem file unreadable/invalid
  PRISM_ERROR_IO(3),

  /// audio device could not be opened or started
  PRISM_ERROR_DEVICE(4),
  PRISM_ERROR_OUT_OF_MEMORY(5);

  final int value;
  const prism_result(this.value);

  static prism_result fromValue(int value) => switch (value) {
        0 => PRISM_OK,
        1 => PRISM_ERROR_INVALID_ARGUMENT,
        2 => PRISM_ERROR_INVALID_STATE,
        3 => PRISM_ERROR_IO,
        4 => PRISM_ERROR_DEVICE,
        5 => PRISM_ERROR_OUT_OF_MEMORY,
        _ => throw ArgumentError('Unknown value for prism_result: $value'),
      };
}

final class prism_core extends ffi.Opaque {}

enum prism_vertical {
  PRISM_VERTICAL_AQADEMIQ(0),
  PRISM_VERTICAL_VENUES(1),
  PRISM_VERTICAL_AUTOMOTIVE(2);

  final int value;
  const prism_vertical(this.value);

  static prism_vertical fromValue(int value) => switch (value) {
        0 => PRISM_VERTICAL_AQADEMIQ,
        1 => PRISM_VERTICAL_VENUES,
        2 => PRISM_VERTICAL_AUTOMOTIVE,
        _ => throw ArgumentError('Unknown value for prism_vertical: $value'),
      };
}

final class prism_config extends ffi.Struct {
  /// Timezone offset in minutes, UTC minus local (JS Date#getTimezoneOffset convention).
  /// The circadian prior works in local hours; hosts refresh it by re-creating the core
  /// (sessions should not span timezone changes).
  @ffi.Int32()
  external int tz_offset_min;

  /// Adapter profile / PSV `vertical` field. v1 implements the aqademiq profile.
  @ffi.Int32()
  external int vertical;

  /// Nominal PSV emit cadence in ms; 0 = spec default (30000 for aqademiq, PSV §7.1).
  @ffi.Int64()
  external int cadence_ms;

  /// Inference wake interval in ms; 0 = default (5000). Mainly for tests.
  @ffi.Int64()
  external int check_interval_ms;

  /// Min |value change| in any PSV dimension forcing an early emit; 0 = default (0.1).
  @ffi.Double()
  external double significant_delta;
}

final class prism_task_deadline extends ffi.Struct {
  /// epoch ms
  @ffi.Int64()
  external int due_ms;

  /// 0 = low, 1 = medium, 2 = high; out of range reads as medium
  @ffi.Int32()
  external int priority;
}

/// --- PSV read-out (for UI) -----------------------------------------------------------
final class prism_psv extends ffi.Struct {
  /// Spec §4.1 dimensions, each value/confidence in [0,1].
  @ffi.Double()
  external double arousal;

  @ffi.Double()
  external double arousal_confidence;

  @ffi.Double()
  external double valence;

  @ffi.Double()
  external double valence_confidence;

  @ffi.Double()
  external double cognitive_load;

  @ffi.Double()
  external double cognitive_load_confidence;

  @ffi.Double()
  external double readiness;

  @ffi.Double()
  external double readiness_confidence;

  @ffi.Int64()
  external int update_timestamp_ms;

  /// Strictly monotonic across the handle's lifetime: the first start's cold-start vector
  /// is 0; a restart's neutral vector CONTINUES the sequence (safe to dedup by it).
  @ffi.Int64()
  external int sequence;

  /// NUL-terminated; empty string = null hint (spec §9)
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Char> mode_hint;
}

const int __has_safe_buffers = 1;

const int __DARWIN_ONLY_64_BIT_INO_T = 1;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_ONLY_VERS_1050 = 1;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

const String __DARWIN_SUF_EXTSN = '\$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_VERS_1050 = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __has_ptrcheck = 0;

const int __has_bounds_safety_attributes = 0;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int __DARWIN_WCHAR_MAX = 2147483647;

const int __DARWIN_WCHAR_MIN = -2147483648;

const int __DARWIN_WEOF = -1;

const int _FORTIFY_SOURCE = 2;

const int NULL = 0;

const int USER_ADDR_NULL = 0;

const int __WORDSIZE = 64;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int PRISM_ABI_VERSION_MAJOR = 0;

const int PRISM_ABI_VERSION_MINOR = 1;

const int PRISM_ABI_VERSION_PATCH = 0;
