// Generated by ffigen from include/prism/prism_core.h — DO NOT EDIT.
// ignore_for_file: type=lint, doc_directive_unknown

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Generated from the Prism Engine core C ABI. DO NOT EDIT by hand.
class PrismCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PrismCoreBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  PrismCoreBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// "MAJOR.MINOR.PATCH" of the linked library. Compare against the macros above.
  ffi.Pointer<ffi.Char> prism_version() {
    return _prism_version();
  }

  late final _prism_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'prism_version');
  late final _prism_version =
      _prism_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Static, human-readable description; never NULL.
  ffi.Pointer<ffi.Char> prism_result_description(
    prism_result result,
  ) {
    return _prism_result_description(
      result.value,
    );
  }

  late final _prism_result_descriptionPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>>(
      'prism_result_description');
  late final _prism_result_description = _prism_result_descriptionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  /// All defaults (aqademiq profile, UTC, spec cadence).
  prism_config prism_config_default() {
    return _prism_config_default();
  }

  late final _prism_config_defaultPtr =
      _lookup<ffi.NativeFunction<prism_config Function()>>(
          'prism_config_default');
  late final _prism_config_default =
      _prism_config_defaultPtr.asFunction<prism_config Function()>();

  /// Create an engine. `config` may be NULL for all defaults. On success writes the new
  /// handle to *out_core. The handle must be released with prism_destroy.
  prism_result prism_create(
    ffi.Pointer<prism_config> config,
    ffi.Pointer<ffi.Pointer<prism_core>> out_core,
  ) {
    return prism_result.fromValue(_prism_create(
      config,
      out_core,
    ));
  }

  late final _prism_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_config>,
              ffi.Pointer<ffi.Pointer<prism_core>>)>>('prism_create');
  late final _prism_create = _prism_createPtr.asFunction<
      int Function(
          ffi.Pointer<prism_config>, ffi.Pointer<ffi.Pointer<prism_core>>)>();

  /// Stops everything still running (inference thread, built-in device) and frees the
  /// handle. NULL is a no-op.
  void prism_destroy(
    ffi.Pointer<prism_core> core,
  ) {
    return _prism_destroy(
      core,
    );
  }

  late final _prism_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<prism_core>)>>(
          'prism_destroy');
  late final _prism_destroy =
      _prism_destroyPtr.asFunction<void Function(ffi.Pointer<prism_core>)>();

  /// Load a scene manifest (scenes.json; stem paths resolve relative to it). Decodes and
  /// preloads every stem of the default scene — file I/O happens HERE, never at render
  /// time. Call once, before prism_start / any rendering. INVALID_STATE after start.
  prism_result prism_load_scene(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<ffi.Char> scenes_json_path,
  ) {
    return prism_result.fromValue(_prism_load_scene(
      core,
      scenes_json_path,
    ));
  }

  late final _prism_load_scenePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>,
              ffi.Pointer<ffi.Char>)>>('prism_load_scene');
  late final _prism_load_scene = _prism_load_scenePtr.asFunction<
      int Function(ffi.Pointer<prism_core>, ffi.Pointer<ffi.Char>)>();

  /// Start the engine: emits the neutral PSV (spec §6) and launches the internal inference
  /// thread (evaluates on the cadence + significant-change rule). Requires a loaded scene.
  /// INVALID_STATE if already started. Restart after prism_stop is allowed; the restart's
  /// neutral vector continues the sequence (see prism_psv.sequence).
  prism_result prism_start(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_start(
      core,
    ));
  }

  late final _prism_startPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>('prism_start');
  late final _prism_start =
      _prism_startPtr.asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// Stop the inference thread (and the built-in device if running). Idempotent.
  prism_result prism_stop(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_stop(
      core,
    ));
  }

  late final _prism_stopPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>('prism_stop');
  late final _prism_stop =
      _prism_stopPtr.asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// --- Event ingress -------------------------------------------------------------------
  /// Platform shells capture raw events and forward them; no inference logic lives on the
  /// host side. Timestamps are epoch milliseconds from the host clock. App identity never
  /// crosses this boundary: a switch is a bare timestamp, idle is a duration, tasks are
  /// due instants plus priorities. Thread-safe; never call from the render callback.
  prism_result prism_report_app_switch(
    ffi.Pointer<prism_core> core,
    int t_ms,
  ) {
    return prism_result.fromValue(_prism_report_app_switch(
      core,
      t_ms,
    ));
  }

  late final _prism_report_app_switchPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<prism_core>, ffi.Int64)>>('prism_report_app_switch');
  late final _prism_report_app_switch = _prism_report_app_switchPtr
      .asFunction<int Function(ffi.Pointer<prism_core>, int)>();

  prism_result prism_report_idle(
    ffi.Pointer<prism_core> core,
    int t_ms,
    int idle_ms,
  ) {
    return prism_result.fromValue(_prism_report_idle(
      core,
      t_ms,
      idle_ms,
    ));
  }

  late final _prism_report_idlePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>, ffi.Int64,
              ffi.Int64)>>('prism_report_idle');
  late final _prism_report_idle = _prism_report_idlePtr
      .asFunction<int Function(ffi.Pointer<prism_core>, int, int)>();

  /// Replace the full task-deadline snapshot (matches how hosts observe task lists).
  /// `tasks` may be NULL when `count` is 0 (an empty list is a valid state). Task lists are
  /// human-scale: count > 4096 is rejected as INVALID_ARGUMENT (this also shields the
  /// boundary from negative lengths cast to size_t). No C++ exception ever crosses this
  /// ABI; internal failures surface as error codes.
  prism_result prism_report_task_deadlines(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<prism_task_deadline> tasks,
    int count,
  ) {
    return prism_result.fromValue(_prism_report_task_deadlines(
      core,
      tasks,
      count,
    ));
  }

  late final _prism_report_task_deadlinesPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(
              ffi.Pointer<prism_core>,
              ffi.Pointer<prism_task_deadline>,
              ffi.Size)>>('prism_report_task_deadlines');
  late final _prism_report_task_deadlines =
      _prism_report_task_deadlinesPtr.asFunction<
          int Function(ffi.Pointer<prism_core>,
              ffi.Pointer<prism_task_deadline>, int)>();

  /// Copy the most recently emitted PSV into *out. INVALID_STATE before prism_start (the
  /// cold-start vector exists from start onward). Thread-safe.
  prism_result prism_get_psv(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<prism_psv> out,
  ) {
    return prism_result.fromValue(_prism_get_psv(
      core,
      out,
    ));
  }

  late final _prism_get_psvPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>,
              ffi.Pointer<prism_psv>)>>('prism_get_psv');
  late final _prism_get_psv = _prism_get_psvPtr.asFunction<
      int Function(ffi.Pointer<prism_core>, ffi.Pointer<prism_psv>)>();

  /// Pin the PSV. Takes effect immediately — the vector is published on return, so the mood
  /// starts moving without waiting for the next inference tick. Ramped by the engine like
  /// any other PSV change; nothing steps. Calling again replaces the current override.
  /// Valid before prism_start (the pinned vector then replaces the cold-start neutral one).
  /// Thread-safe.
  prism_result prism_set_mood_override(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<prism_mood_override> override_in,
  ) {
    return prism_result.fromValue(_prism_set_mood_override(
      core,
      override_in,
    ));
  }

  late final _prism_set_mood_overridePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>,
              ffi.Pointer<prism_mood_override>)>>('prism_set_mood_override');
  late final _prism_set_mood_override = _prism_set_mood_overridePtr.asFunction<
      int Function(
          ffi.Pointer<prism_core>, ffi.Pointer<prism_mood_override>)>();

  /// Release the pin and hand control back to the PCE, which resumes at its next tick.
  /// Idempotent: clearing when nothing is pinned succeeds and does nothing. Thread-safe.
  prism_result prism_clear_mood_override(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_clear_mood_override(
      core,
    ));
  }

  late final _prism_clear_mood_overridePtr = _lookup<
          ffi
          .NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>(
      'prism_clear_mood_override');
  late final _prism_clear_mood_override = _prism_clear_mood_overridePtr
      .asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// Control thread only, same class as prism_load_scene: it BLOCKS for the decode, because
  /// the file I/O has to happen somewhere and the render path is not allowed to do it. It
  /// returns as soon as the swap is armed; the crossfade itself runs on the audio thread.
  ///
  /// The armed command is consumed by whatever renders — prism_render or the built-in
  /// device — so a handle that is not rendering will hold it and keep reporting BUSY until
  /// it does. prism_stop drops any unconsumed swap.
  ///
  /// PRISM_ERROR_INVALID_STATE     no scene loaded yet
  /// PRISM_ERROR_BUSY              a crossfade is still in flight
  /// PRISM_ERROR_INVALID_ARGUMENT  null argument, or the new scene's sample rate differs
  /// PRISM_ERROR_IO / _OUT_OF_MEMORY  as prism_load_scene
  prism_result prism_crossfade_scene(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<prism_scene_swap> swap,
  ) {
    return prism_result.fromValue(_prism_crossfade_scene(
      core,
      swap,
    ));
  }

  late final _prism_crossfade_scenePtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>,
              ffi.Pointer<prism_scene_swap>)>>('prism_crossfade_scene');
  late final _prism_crossfade_scene = _prism_crossfade_scenePtr.asFunction<
      int Function(ffi.Pointer<prism_core>, ffi.Pointer<prism_scene_swap>)>();

  /// Non-zero while a crossfade is armed or running. Safe from any thread; one atomic load.
  /// Hosts use it to avoid asking for a mood change that would only come back BUSY.
  int prism_crossfade_active(
    ffi.Pointer<prism_core> core,
  ) {
    return _prism_crossfade_active(
      core,
    );
  }

  late final _prism_crossfade_activePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<prism_core>)>>(
          'prism_crossfade_active');
  late final _prism_crossfade_active = _prism_crossfade_activePtr
      .asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// Sample rate of the loaded scene's stems (0 before a scene is loaded). Mono float32.
  int prism_sample_rate(
    ffi.Pointer<prism_core> core,
  ) {
    return _prism_sample_rate(
      core,
    );
  }

  late final _prism_sample_ratePtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Pointer<prism_core>)>>(
          'prism_sample_rate');
  late final _prism_sample_rate =
      _prism_sample_ratePtr.asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// Render `frame_count` mono float32 frames into out_frames. Real-time safe: wait-free,
  /// no allocation, no locks, no I/O, no logging. Single audio thread only. Before a scene
  /// is loaded, fills silence and returns INVALID_STATE.
  prism_result prism_render(
    ffi.Pointer<prism_core> core,
    ffi.Pointer<ffi.Float> out_frames,
    int frame_count,
  ) {
    return prism_result.fromValue(_prism_render(
      core,
      out_frames,
      frame_count,
    ));
  }

  late final _prism_renderPtr = _lookup<
      ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<prism_core>,
              ffi.Pointer<ffi.Float>, ffi.Uint32)>>('prism_render');
  late final _prism_render = _prism_renderPtr.asFunction<
      int Function(ffi.Pointer<prism_core>, ffi.Pointer<ffi.Float>, int)>();

  /// Open and start the built-in playback device (renders internally; do not also call
  /// prism_render). Requires a loaded scene. INVALID_STATE if already running.
  prism_result prism_device_start(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_device_start(
      core,
    ));
  }

  late final _prism_device_startPtr = _lookup<
          ffi
          .NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>(
      'prism_device_start');
  late final _prism_device_start = _prism_device_startPtr
      .asFunction<int Function(ffi.Pointer<prism_core>)>();

  /// Stop and close the built-in device. Idempotent.
  prism_result prism_device_stop(
    ffi.Pointer<prism_core> core,
  ) {
    return prism_result.fromValue(_prism_device_stop(
      core,
    ));
  }

  late final _prism_device_stopPtr = _lookup<
          ffi
          .NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<prism_core>)>>(
      'prism_device_stop');
  late final _prism_device_stop =
      _prism_device_stopPtr.asFunction<int Function(ffi.Pointer<prism_core>)>();
}

enum prism_result {
  PRISM_OK(0),

  /// null/malformed parameter
  PRISM_ERROR_INVALID_ARGUMENT(1),

  /// call violates the lifecycle (see per-function docs)
  PRISM_ERROR_INVALID_STATE(2),

  /// scene manifest or stem file unreadable/invalid
  PRISM_ERROR_IO(3),

  /// audio device could not be opened or started
  PRISM_ERROR_DEVICE(4),
  PRISM_ERROR_OUT_OF_MEMORY(5),

  /// a scene crossfade is already in flight
  PRISM_ERROR_BUSY(6);

  final int value;
  const prism_result(this.value);

  static prism_result fromValue(int value) => switch (value) {
        0 => PRISM_OK,
        1 => PRISM_ERROR_INVALID_ARGUMENT,
        2 => PRISM_ERROR_INVALID_STATE,
        3 => PRISM_ERROR_IO,
        4 => PRISM_ERROR_DEVICE,
        5 => PRISM_ERROR_OUT_OF_MEMORY,
        6 => PRISM_ERROR_BUSY,
        _ => throw ArgumentError('Unknown value for prism_result: $value'),
      };
}

final class prism_core extends ffi.Opaque {}

enum prism_vertical {
  PRISM_VERTICAL_AQADEMIQ(0),
  PRISM_VERTICAL_VENUES(1),
  PRISM_VERTICAL_AUTOMOTIVE(2);

  final int value;
  const prism_vertical(this.value);

  static prism_vertical fromValue(int value) => switch (value) {
        0 => PRISM_VERTICAL_AQADEMIQ,
        1 => PRISM_VERTICAL_VENUES,
        2 => PRISM_VERTICAL_AUTOMOTIVE,
        _ => throw ArgumentError('Unknown value for prism_vertical: $value'),
      };
}

final class prism_config extends ffi.Struct {
  /// Timezone offset in minutes, UTC minus local (JS Date#getTimezoneOffset convention).
  /// The circadian prior works in local hours; hosts refresh it by re-creating the core
  /// (sessions should not span timezone changes).
  @ffi.Int32()
  external int tz_offset_min;

  /// Adapter profile / PSV `vertical` field. v1 implements the aqademiq profile.
  @ffi.Int32()
  external int vertical;

  /// Nominal PSV emit cadence in ms; 0 = spec default (30000 for aqademiq, PSV §7.1).
  @ffi.Int64()
  external int cadence_ms;

  /// Inference wake interval in ms; 0 = default (5000). Mainly for tests.
  @ffi.Int64()
  external int check_interval_ms;

  /// Min |value change| in any PSV dimension forcing an early emit; 0 = default (0.1).
  @ffi.Double()
  external double significant_delta;
}

final class prism_task_deadline extends ffi.Struct {
  /// epoch ms
  @ffi.Int64()
  external int due_ms;

  /// 0 = low, 1 = medium, 2 = high; out of range reads as medium
  @ffi.Int32()
  external int priority;
}

/// --- PSV read-out (for UI) -----------------------------------------------------------
final class prism_psv extends ffi.Struct {
  /// Spec §4.1 dimensions, each value/confidence in [0,1].
  @ffi.Double()
  external double arousal;

  @ffi.Double()
  external double arousal_confidence;

  @ffi.Double()
  external double valence;

  @ffi.Double()
  external double valence_confidence;

  @ffi.Double()
  external double cognitive_load;

  @ffi.Double()
  external double cognitive_load_confidence;

  @ffi.Double()
  external double readiness;

  @ffi.Double()
  external double readiness_confidence;

  @ffi.Int64()
  external int update_timestamp_ms;

  /// Strictly monotonic across the handle's lifetime: the first start's cold-start vector
  /// is 0; a restart's neutral vector CONTINUES the sequence (safe to dedup by it).
  @ffi.Int64()
  external int sequence;

  /// NUL-terminated; empty string = null hint (spec §9)
  @ffi.Array.multi([24])
  external ffi.Array<ffi.Char> mode_hint;
}

/// --- Host mood override ---------------------------------------------------------------
/// Prism Venues puts a human in the loop: a manager taps one of six named moods and the
/// room must follow. The PCE infers state, it does not take requests, so there was no way
/// to express that. This pins the vector the audio engine consumes until it is cleared.
///
/// It is NOT a volume or scene control. A mood is a point in PSV space, so a pinned mood
/// reaches the audio the same way an inferred one does — through the §5 mapping. High
/// arousal opens the density gates and raises the mapped level; low arousal leaves the
/// scene sparse and quiet. Nothing bypasses the mapping, the smoothing, or the limiter,
/// and no DSP constant moves.
///
/// Confidence is explicit because it is load-bearing: every consumer blends toward
/// neutral as confidence falls (spec §8.1), so an override published at low confidence
/// would be pulled back to the middle and barely change the sound. A manual pin is a
/// statement of fact about the room, so hosts should pass 1.0 unless they mean otherwise.
///
/// The firewall is untouched: this sets the PSV the PCE would have emitted, at the same
/// publish point, and the audio engine still sees nothing but a PSV. The render thread is
/// untouched too — the override is applied on the control side, before the atomic handoff.
///
/// While an override is set the PCE keeps running and its output keeps being discarded;
/// clearing restores inferred state from the next tick.
final class prism_mood_override extends ffi.Struct {
  /// NUL-terminated hint naming the mood, e.g. "venue_peak". Copied, not retained; may be
  /// NULL or "" for no hint. Longer than 23 chars is INVALID_ARGUMENT rather than being
  /// silently truncated into a different mood.
  external ffi.Pointer<ffi.Char> mode_hint;

  /// Spec §4.1 dimensions, each in [0,1]. Out of range is INVALID_ARGUMENT.
  @ffi.Double()
  external double arousal;

  @ffi.Double()
  external double valence;

  @ffi.Double()
  external double cognitive_load;

  @ffi.Double()
  external double readiness;

  /// Applied to all four dimensions, in [0,1]. Use 1.0 for a manual pin.
  @ffi.Double()
  external double confidence;
}

/// --- Gapless scene change --------------------------------------------------------------
/// prism_load_scene binds a scene to a handle for the handle's LIFE, and prism_stop does
/// not release it. That is deliberate and unchanged: it is what lets the render path own
/// fully decoded buffers and never touch disk.
///
/// This is the other door. A mood is a different scene — a different set of stems — so
/// moving between moods means holding two at once. The host decodes the incoming scene on
/// its own thread and hands the engine an equal-power crossfade between the two. The
/// outgoing scene is released on a CONTROL thread once the audio thread has finished with
/// it, never on the render path.
final class prism_scene_swap extends ffi.Struct {
  /// Manifest path, exactly as prism_load_scene takes it; stems resolve relative to it.
  /// Its sample rate must equal the loaded scene's — the device is already open at that
  /// rate and there is no resampler, so a mismatch is INVALID_ARGUMENT.
  external ffi.Pointer<ffi.Char> scenes_json_path;

  /// Length of the equal-power overlap, in milliseconds. 0 selects the engine default
  /// (1500 ms). Clamped to [50, 120000]. This is the "how slowly it eases" control.
  @ffi.Int64()
  external int crossfade_ms;

  /// Non-zero: start the overlap at the outgoing scene's next loop boundary, so the
  /// material leaving is never cut mid-phrase. Musically the right default, but it costs
  /// up to one loop period of waiting before anything is audible — 16 s with the Venues
  /// stems, which is why the shortest transition setting should pass zero here and accept
  /// a start at the next block instead.
  @ffi.Int32()
  external int align_to_loop_boundary;
}

const int PRISM_ABI_VERSION_MAJOR = 0;

const int PRISM_ABI_VERSION_MINOR = 3;

const int PRISM_ABI_VERSION_PATCH = 0;
